---
apiVersion: v1
kind: Service
metadata:
  name: aws9-service-blog
  namespace: aws9c
spec:
  selector:
    color: black  # 이 label을 가진 Pod와 연결
  ports:
    - protocol: TCP
      port: 80         # 외부에서 접근할 포트
      targetPort: 80   # 컨테이너 내부 포트
  type: LoadBalancer   # 외부에서 접근 가능한 LoadBalancer 타입 서비스
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9-deploy-blog
  namespace: aws9c
spec:
  selector:
    matchLabels:
      color: black  # 이 라벨을 가진 Pod들을 대상으로 관리
  template:
    metadata:
      labels:
        color: black  # Pod에 적용될 라벨 (Service와 연결되기 위해 동일해야 함)
    spec:
      containers:
        - name: aws9c-blog
          image: brian24/aws9:blue  # 사용될 컨테이너 이미지
          ports:
            - containerPort: 80     # 컨테이너에서 열리는 포트
          resources:
            limits:
              memory: "64Mi"        # 최대 메모리 사용량
              cpu: "500m"           # 최대 CPU 사용량
            requests:
              memory: "32Mi"        # 최소 보장 메모리
              cpu: "250m"           # 최소 보장 CPU
